### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dinosaw** [richard4339/destiny2-php#3]
Hello,

I was wanting to provision this on a server, but I'm a little confused on how to get it going. I'm running PHP7 on my server, and have ran the composer command:

```
$ composer require richard4339/destiny2-php
Using version ^0.2.4 for richard4339/destiny2-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)         
  - Installing richard4339/destiny2-php (v0.2.4): Downloading (100%)         
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files
```
After this part, I'm not sure what I need to do. It seems to have only created a `vendor` directory on the server. Do you mind elaborating a bit on how to get this up and going? I'm essentially just wanting to create a simple website/app with Xur information (location/stock). Thanks!

**Comment by richard4339** [comment]
You can’t get Xur’s location anymore, technically you never could but you could assume it was the flashpoint. I’ve got some code where I got his inventory before l, I’ll see if I can find it.

**Comment by richard4339** [comment]
Basic usage is just something like this, replacing in your own API key.

`<?php

require 'vendor/autoload.php';

$client = new \Destiny\Client('[YOUR API KEY]');

$results = $client->getClanMembers(3199633);

var_dump($results);`

Xur requires a lot more because vendors require you to authenticate as the user for which you want to see Xur's inventory. I've got the code in the function for retrieving him.

`$client->getVendor(BungieMembershipType::TIGERPSN, '12345', '67890', '2190858386', DestinyComponentType::VENDORS);`

2190858386 is his Vendor ID. However, you have to first successfully do oauth and you also have to process the Bungie data download for it to make sense. It's a lot more than I can simply put here, you'd need a very extensive walkthrough. @lowlines has good info on his page https://destinydevs.github.io/BungieNetPlatform/docs/Authentication and there's also https://destiny.plumbing who even has the first portion of what I said you would need (getting Xur's item hashes) done https://api.destiny.plumbing/xur (assuming it is up to date).
